[tool.poetry]
name = "lambda-with-poetry"
version = "0.1.0"
description = ""
authors = ["budi-kurniawan <budi2020@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
